# -*- coding: utf-8 -*-
import sqlite3
from pathlib import Path

DB_PATH = Path(__file__).parent / "incident_report.db"

SEED_DATA = [
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPISE009", "Incorrect Bag Fee Setup"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPBF010", "Incorrect UPC on DAT File"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPBE001", "SYSTEM * VPOS* Blank Exception"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPCIL003", "SYSTEM * VPOS* Controlled Item Limit"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPCE004", "SYSTEM * VPOS* CONFIG_ERROR:FACTORY_ERROR"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPDI005", "SYSTEM * VPOS* Departmental item is not eligible for fix"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPDC006", "SYSTEM * VPOS* Ecom/Shopsite Customers Not Receiving J4U Discount (Missed Discount)"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPEU007", "SYSTEM * VPOS* error unmarshalling return header"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPFD008", "SYSTEM * VPOS* First Data Issue"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPIU011", "SYSTEM * VPOS* Incorrect UPC on dat file"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPIDF012", "SYSTEM * VPOS* Invalid CC exception - incomplete dat file"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPIKS015", "SYSTEM * VPOS* Invalid Key Sequence"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPIR016", "SYSTEM * VPOS* Invalid 4690 Item Record"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPIA017", "SYSTEM * VPOS* INVALID_ARGUMENT:DATA_OUT_OF_RANGE"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPIL018", "SYSTEM * VPOS* Item Link to itself in Controller"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPQP020", "SYSTEM * VPOS* Item Picked not matching the Quantity Picked in Dat file"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VP021", "SYSTEM * VPOS* Items with Subs are showing OOS in receipts"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPLIP022", "SYSTEM * VPOS* LINKED_ITEM_ERROR:INVALID_PRICE"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPLIS023", "SYSTEM * VPOS* LINKED_ITEM_ERROR:ITEM_NOT_FOR_SALE"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPLUL024", "SYSTEM * VPOS* LINKED_ITEM_ERROR - approaching the upper limit on the number of items allowed in a transaction"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPLWQ025", "SYSTEM * VPOS* Looping/Repeating Weight & Quantity Value in Fixit"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VP026", "SYSTEM * VPOS* Missing UPC on dat file"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VP027", "SYSTEM * VPOS* Missing/Incomplete Items in an Order"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VP028", "SYSTEM * VPOS* Mobile Link Refund not working"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VP029", "SYSTEM * VPOS* Monopoly issue"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPNB030", "SYSTEM * VPOS* Negative Balance"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VP031", "SYSTEM * VPOS* NO_ERROR_TEXT_AVAILABLE"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPNIC032", "SYSTEM * VPOS* NO_ITEM_MATCH_FOR_COUPON"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VP033", "SYSTEM * VPOS* No Value in XML"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VP034", "SYSTEM * VPOS* OOS Items being charged"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VP035", "SYSTEM * VPOS* OOS items not showing in receipt"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VP036", "SYSTEM * VPOS* Order limit error"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPOLE037", "SYSTEM * VPOS* Order Too Large Exception"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPOLI038", "SYSTEM * VPOS* Order too large (incorrect upc)"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VP039", "SYSTEM * VPOS* Page cannot be displayed"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPG040", "SYSTEM * VPOS* Payment Gateway Internal Error"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VP041", "SYSTEM * VPOS* PAYMENT MAY ALREADY BE EXECUTED"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VP042", "SYSTEM * VPOS* PROCEDURE_NOT_ALLOWED:LOYALTY_NUMBER_REQUIRED"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VP043", "SYSTEM * VPOS* POS application is busy and automation API is locked"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VP044", "SYSTEM * VPOS* Receipt Not Printing"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VP045", "SYSTEM * VPOS* Regulated form not printing"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VP046", "SYSTEM * VPOS* Remote Exception"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VP047", "SYSTEM * VPOS* Status Code: 409 - Duplicate transaction issue"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSIE048", "SYSTEM * VPOS* SYSTEM_INTERNAL_ERROR"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSIR049", "SYSTEM * VPOS* SYSTEM_INTERNAL_ERROR-Refund"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VP050", "SYSTEM * VPOS* Technical Error Message: Error writing price to unprocessed order file"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VP051", "SYSTEM * VPOS* Technical Error Message: The transaction is too large and must be ended"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VP052", "SYSTEM * VPOS* technical issue while tokenizing credit card"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPTRI054", "SYSTEM * VPOS* Item cannot legally be sold (Incorrect UPC)"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPEP056", "SYSTEM * VPOS* Receipt stuck in EcomPrint folder"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPIIS058", "SYSTEM * VPOS * VPOS IIS issue"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPDI059", "SYSTEM * VPOS Stopping due to data issue"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPCR060", "SYSTEM * VPOS Stopped - css restart"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSS061", "SYSTEM * VPOS Stopped - service stopped"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSRS062", "SYSTEM * VPOS* Vtill Stuck in Running Status"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSRC063", "SYSTEM * VPOS* Vtill Stuck in Running - css restart"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSRD064", "SYSTEM * VPOS* Vtill Stuck in Running - stuck transaction in DD"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPDSI065", "SYSTEM * VPOS* Drive Space Issue"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPTO066", "SYSTEM * VPOS* Vtill Exception B034 Error Processing Tender Override Item"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPAF067", "SYSTEM * VPOS* POS_APP_FAILURE:FILE_IO_ERROR"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPVD068", "SYSTEM * VPOS is down"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPMD069", "SYSTEM * VPOS* SELL_ITEM_BEFORE_MARKDOWN:INVALID_ARGUMENT"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPCF070", "SYSTEM * VPOS* store number is missing in config file"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPDD071", "SYSTEM * VPOS* Orders are not processing in VTill - DD is down"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPNUL074", "SYSTEM * VPOS * PAYMENT EXCEPTION - Invalid Card Holders Name"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPEP075", "SYSTEM * VPOS * Orders stuck in PEPEReprocess Folder"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPJRE076", "SYSTEM * VPOS * VPOS Stopped - missing openJRE"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPDT077", "SYSTEM * VPOS * POS_DISPLAY_TEXT Exception"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPINFND078", "SYSTEM * VPOS * Item Not Found - Item Description is No Description"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSDC079", "SYSTEM * VPOS * Session Not Available (Connection Status: DISCONNECTED): AddTender"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPMAN080", "SYSTEM * VPOS * Missed Savings due to manual charging"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSVR081", "SYSTEM * VPOS * Incorrect server time - Item cannot legally be sold exception"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSRF082", "SYSTEM * VPOS * Vtill Stuck in Running Status - Refund issue"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPCTRA083", "SYSTEM * VPOS * Alcohol item - Controlled Item Limit Exception"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPCPDF084", "SYSTEM * VPOS * Clean Receipt - Missing PDF receipt"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPCRMS085", "SYSTEM * VPOS * Clean Receipt - Missing Order in VPOS"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPDTIP086", "SYSTEM * VPOS * Item Not Found - Driver Tip"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPEN087", "SYSTEM * VPOS * PAYMENT EXCEPTION - Technical Error Message: null"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPCRRR088", "SYSTEM * VPOS * Clean Receipt - Reboot/Restart of Services Required before repost of Missing Orders"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPUSNP089", "SYSTEM * VPOS * Unable to process SNAP Tenders"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPCHSP253", "SYSTEM * VPOS * Chicago Store - Unable to process SNAP Tenders"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPEX090", "SYSTEM * VPOS * PAYMENT EXCEPTION * Technical Error Message - Txn has invalid [Status]: Cannot be incremented"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSNP091", "SYSTEM * VPOS * SNAP_REFUND_ERROR SNAP-EBT: No transaction id is available for process refund"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPEX092", "SYSTEM * VPOS * PAYMENT EXCEPTION - Payment gateway response: invalid format"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSIE093", "SYSTEM * VPOS * SYSTEM_INTERNAL_ERROR - due to corrupted PaymentHistory xml in log folder"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSNP094", "SYSTEM * VPOS * SNAP_REFUND_ERROR SNAP-EBT: Unexpected error while making SNAP Refund service"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPEBR095", "SYSTEM * VPOS * PAYMENT EXCEPTION - Technical Error Message: 400 BAD_REQUEST"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPCRK096", "SYSTEM * VPOS * Orders Not Flowing to VTILL - Kafka Internal Server Error"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPDCR098", "SYSTEM * VPOS * Delayed Clean Receipts"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPBAG099", "SYSTEM * VPOS * Item Not Found - Bag Fee"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPDSNP100", "SYSTEM * VPOS * SNAP-EBT: Duplicate refund transaction found"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSNP101", "SYSTEM * VPOS * SNAP-EBT: Amount of refund is greater than amount authorized"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPKCM102", "SYSTEM * VPOS * Orders not flowing to VTill - Kafka consumer is down"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPFLSH103", "SYSTEM * VPOS* Item Not Found - Flash Delivery Fee"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPIE014", "SYSTEM * VPOS * invalid entity"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPIE015", "SYSTEM * VPOS * invalid entity - Version Mismatch - Missing fulfilledUpc and shortquantity field from JSON"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPOP007", "SYSTEM * VPOS * Switch store receipt printer"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPRC104", "SYSTEM * VPOS * Multiple orders stuck in processing - missing config"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSIEE205", "SYSTEM * VPOS * SYSTEM INTERNAL ERROR - Error reposting order to Transparency/Echo"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPJPR206", "SYSTEM * VPOS * JSON parsing issue - Order is in VPOS but not showing in UI"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSNP207", "SYSTEM * VPOS * SNAP-EBT: Fully Refunded in ERUMS but complete in VPOS"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPREG208", "SYSTEM * VPOS * Regulated Item Form printing twice"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSNPS209", "SYSTEM * VPOS * Receipt for SNAPv1 order is not showing substitutions"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPIICN210", "SYSTEM * VPOS * Payment Exception: Invalid inputs in customer name"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSCF211", "SYSTEM * VPOS * Store Vtill Config Issue"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPIID212", "SYSTEM * VPOS * Incorrect item description on order receipt"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPOS213", "SYSTEM * VPOS * POS application not in state to perform start transaction"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPMPL214", "SYSTEM * VPOS * Stuck in DelayedReceipt due to missing POSLOG"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSIE215", "SYSTEM * VPOS * SYSTEM_INTERNAL_ERROR Unexpected Exception occurred while processing the order"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSIE216", "SYSTEM * VPOS * SYSTEM_INTERNAL_ERROR - Unable to generate receipt"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPDTPDE217", "SYSTEM * VPOS * POS_DISPLAY_EXCEPTION - DTILL Order"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPEBTBF218", "SYSTEM * VPOS * EBT Order - Bag Fee in order receipt"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPINFR220", "SYSTEM * VPOS * Item Not Found - Refund"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPDTN221", "SYSTEM * VPOS * Tilling Exception due to Negative Balance"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPONF222", "SYSTEM * VPOS * Refund Exception Order Not Found"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPUPR223", "SYSTEM * VPOS * Payment Exception: Unable to process a refund"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPRSB224", "SYSTEM * VPOS * Receipts are not showing substitutions"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPIDR225", "SYSTEM * VPOS * Incorrect item descriptions in PDF Digital Receipts but not in RPT"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPMOF226", "SYSTEM * VPOS * Minimum order fee $3.95 was charged to customer"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPDE227", "SYSTEM * VPOS * PAYMENT_DECLINE Exception - app issue"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPEP228", "SYSTEM * VPOS * PAYMENT EXCEPTION - Precondition failed"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPIE0R16", "SYSTEM * VPOS * invalid entity - refund"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPFPF229", "SYSTEM * VPOS* Item Not Found - Flash Pickup Fee"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPNEKS230", "SYSTEM * VPOS * A numeric entry in the key sequence is too large or too small"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSIEP231", "SYSTEM * VPOS * SYSTEM_INTERNAL_ERROR: PEPE Service Internal Error"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPITME232", "SYSTEM * VPOS * Incorrect Exception Time in VPOS UI"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPTENF233", "SYSTEM * VPOS * TILLING EXCEPTION - 404 Not Found from POST - APIM accumulator link"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPTETR234", "SYSTEM * VPOS * TILLING EXCEPTION - Order with restricted item alcohol - not automatically reprocessed after restriction time"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSLT235", "SYSTEM * VPOS * Spirit Tax incorrect charges"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPACE236", "SYSTEM * VPOS * ACEItemEntryActionImpl.performAction(): POS application not in proper substate to perform item entry."),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPSE237", "SYSTEM * VPOS * POS_SYSTEM_ERROR"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPSEPAY250", "SYSTEM * VPOS * POS_SYSTEM_ERROR - Paypal"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPSESM257", "SYSTEM * VPOS * POS_SYSTEM_ERROR - SETTLEMENT MISMATCH"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPFCO238", "SYSTEM * VPOS * FactoryImpl.createObject(SafewayB062ErrorHelper)"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPOPE239", "SYSTEM * VPOS * PRICING_EXCEPTION"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPTILL240", "SYSTEM * VPOS * Tilling Exception - Mandatory attributes are missing"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPEX241", "SYSTEM * VPOS * PRICING_EXCEPTION - No item description"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPVR242", "SYSTEM * VPOS * Price value required"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPASI243", "SYSTEM * VPOS * Order was processed as SNAP 1.0 when store should only have SNAP 2.0 active"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPTKM244", "SYSTEM * VPOS * Tilling Exception - Key details are missing from the order. Please create an incident with IT."),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPRIT245", "SYSTEM * VPOS * Regulated items orders are tilling out before legal selling hours"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPSR246", "SYSTEM * VPOS * POS_SYSTEM_ERROR - Refund"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPJSN247", "SYSTEM * VPOS * JSON PARSING ERROR"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPSER248", "SYSTEM * VPOS * Payment processed successfully. Error encountered while generating receipt."),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPRFF249", "SYSTEM * VPOS * Unable to refund recently completed orders in VPOS"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPAY251", "SYSTEM * VPOS* PAYMENT MAY ALREADY BE EXECUTED - Paypal"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPRC255", "SYSTEM * VPOS * CCT PRICING EXCEPTION FIXED - Order displays 2 status on Vtill"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPLN256", "SYSTEM * VPOS * POS SYSTEM ERROR - LOYALTY_NUMBER_REQUIRED"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPTMF257", "SYSTEM * VPOS * Tilling Exception - missing fulfilledUpc"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSOR258", "SYSTEM * VPOS * Orders stuck in Ready status - CSS & services restart"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPTA259", "SYSTEM * VPOS * PAYMENT_EXCEPTION - Please create an incident with IT - tenderAllocationSummary have 0.0 amount."),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPTD260", "SYSTEM * VPOS* Tender Decline - Customer name is missing causing invalid schema"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPJPE261", "SYSTEM * VPOS * JSON PARSING ERROR - Error while parsing order items, String index out of range: 3"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPJPE262", "SYSTEM * VPOS * JSON PARSING ERROR - missing fulfilled UPC"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPDTR263", "SYSTEM * VPOS * POS_DISPLAY_TEXT - refund"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPEP264", "SYSTEM * VPOS * PAYMENT_EXCEPTION - Please create an incident with IT - Declined Paypal"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPTKM265", "SYSTEM * VPOS * Tilling Exception - Key details are missing from the order. Please create an incident with IT. - schema validation"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPOIRI266", "SYSTEM * VPOS * Order Itemization in Receipt is Incomplete/missing"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPREE267", "SYSTEM * VPOS * REMOTE_EXCEPTION - Error unmarshaling return header; nested exception is: java.net.SocketTimeoutException:"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPODP268", "SYSTEM * VPOS * Overcharged order due to pre auth hold"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPOFF269", "SYSTEM * VPOS * Payment Exception - Please create an incident with IT - EBT refund after FF failed; CC success"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPOFS270", "SYSTEM * VPOS * Payment Exception - Please create an incident with IT - EBT refund after FF success; CC Declined"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPOFC271", "SYSTEM * VPOS * Payment Exception - Please create an incident with IT - EBT refund after FF success; Paypal Declined"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPOND272", "SYSTEM * VPOS * Payment Exception - Please create an incident with IT - No declined payment record in OCSE/OSPG DB"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPEXIPO273", "SYSTEM * VPOS * PRICING_EXCEPTION - ITEM_PRICE_OVERCHARGE"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPACEADC274", "SYSTEM * VPOS * ACEApplyDelayedCouponsActionImpl.performAction(): POS application not in proper substate to apply delayed coupons."),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPTME275", "SYSTEM * VPOS * TOO_MANY_ERRORS ErrorHandler.handleSpecificError(): The maximum number of errors to handle was exceeded."),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSDGT276", "SYSTEM * VPOS * Session Not Ready (Connection status: DISCONNECTED): GetTotals"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPEOSE277", "SYSTEM * VPOS * PEPE_ORDER_SAVINGS_ERROR - Order Savings not applied. To be reprocessed."),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPTEMIP278", "SYSTEM * VPOS * TILLING_EXCEPTION: Key details are missing from the order. Please create an incident with IT. - Missing Item Price"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPTEMEP279", "SYSTEM * VPOS * TILLING_EXCEPTION: Key details are missing from the order. Please create an incident with IT. - Missing Extended Price"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPTEMCN280", "SYSTEM * VPOS * TILLING_EXCEPTION: Key details are missing from the order. Please create an incident with IT. - Missing Customer Name"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPEBNI281", "SYSTEM * VPOS* PAYMENT_EXCEPTION - Please create an incident with IT - BannerCash Issue"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPTEMA282", "SYSTEM * VPOS * TILLING_EXCEPTION: Key details are missing from the order. Please create an incident with IT. - Missing Customer Address"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPTEMPST283", "SYSTEM * VPOS * TILLING_EXCEPTION: Key details are missing from the order. Please create an incident with IT. - Missing PaymentSubType"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPSBR284", "SYSTEM * VPOS * Orders Not Processing in PSBR App"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPPEDRS285", "SYSTEM * VPOS* PAYMENT_EXCEPTION - Please create an incident with IT - Declined Charge in Direct Spend"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPST065", "SYSTEM * VPOS * Service TrustedInstaller is DOWN"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSV066", "SYSTEM * VPOS * Service VPOSACE is DOWN"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSP067", "SYSTEM * VPOS * Service POSBC is DOWN"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSW068", "SYSTEM * VPOS * Service W3SVC is DOWN"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSO069", "SYSTEM * VPOS * Service OSFL is DOWN"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPSR097", "SYSTEM * VPOS * Service REWRITE is DOWN"),
    ("SYSTEM", "VPOS - Virtual Point of Sale System (OSVP)", "VPOP003", "OPS * VPOS * Refund Request"),
    ("OPS", "VPOS - Virtual Point of Sale System (OSVP)", "VPOP009", "OPS * VPOS * Item Not Found - Training on how to fix the exception"),
    ("OPS", "VPOS - Virtual Point of Sale System (OSVP)", "VPLEG072", "OPS * VPOS * Item cannot legally be sold exception - order contains alcohol"),
    ("OPS", "VPOS - Virtual Point of Sale System (OSVP)", "VPOP010", "OPS * VPOS * Refund receipt not printing"),
    ("OPS", "VPOS - Virtual Point of Sale System (OSVP)", "VPOP012", "OPS * VPOS * Unable to login to Refund page"),
    ("OPS", "VPOS - Virtual Point of Sale System (OSVP)", "VPOP013", "OPS * VPOS * Request to Add Van ID in Clean Receipt"),
    ("OPS", "VPOS - Virtual Point of Sale System (OSVP)", "VPTRR055OP", "OPS * VPOS* Item cannot legally be sold exception (Recalled Item)"),
    ("OPS", "VPOS - Virtual Point of Sale System (OSVP)", "VPOP011", "OPS * VPOS * PAYMENT EXCEPTION - Refund is greater than amount charged"),
    ("OPS", "VPOS - Virtual Point of Sale System (OSVP)", "VPOP014", "OPS * VPOS * PAYMENT_DECLINE Exception - declined card"),
    ("OPS", "VPOS - Virtual Point of Sale System (OSVP)", "VPOP015", "OPS * VPOS * PRICING_EXCEPTION - Training on how to fix the exception"),
    ("OPS", "VPOS - Virtual Point of Sale System (OSVP)", "VPOP016", "OPS * VPOS * Remove order in exception from Vtill request"),
    ("OPS", "VPOS - Virtual Point of Sale System (OSVP)", "VPOP017", "OPS * VPOS * Clear print queue job request"),
    ("OPS", "VPOS - Virtual Point of Sale System (OSVP)", "VPOP018", "OPS * VPOS * Store Inquiry on order in PICKUP READY in Vtill"),
    ("OPS", "VPOS - Virtual Point of Sale System (OSVP)", "VPOP019", "OPS * VPOS * Manual charging request"),
    ("OPS", "VPOS - Virtual Point of Sale System (OSVP)", "VPOP020", "OPS * VPOS * Tilling Exception - order contains alcohol"),
    ("OPS", "VPOS - Virtual Point of Sale System (OSVP)", "VPOP021", "OPS * VPOS * Store inquiry on DTILL UI Login"),
    ("PE", "VPOS - Virtual Point of Sale System (OSVP)", "VPOP002", "PE * VPOS * Order Redrop in VTill Request"),
    ("PE", "VPOS - Virtual Point of Sale System (OSVP)", "VPOP005", "PE * VPOS * Removed items requested by customer"),
    ("PE", "VPOS - Virtual Point of Sale System (OSVP)", "VPCC013", "PE * VPOS * Invalid Club card number"),
    ("PE", "VPOS - Virtual Point of Sale System (OSVP)", "VPRFW057", "PE * VPOS * Refund Exception Weight value is required"),
    ("SYSTEM", "Omni Channel Snap & EBT Payments (OCSE)", "OCSEPS001", "SYSTEM * OCSE * SNAP EBT WRITE OFF - Priced-Scale"),
    ("SYSTEM", "Omni Channel Snap & EBT Payments (OCSE)", "OCSEPA002", "SYSTEM * OCSE * SNAP EBT WRITE OFF - Packed with diff wt."),
    ("SYSTEM", "Omni Channel Snap & EBT Payments (OCSE)", "OCSEPE003", "SYSTEM * OCSE * SNAP EBT WRITE OFF - Priced Each"),
    ("SYSTEM", "Omni Channel Snap & EBT Payments (OCSE)", "OCSEPT004", "SYSTEM * OCSE * SNAP EBT WRITE OFF - Price-each totalled"),
    ("SYSTEM", "Omni Channel Snap & EBT Payments (OCSE)", "OCSESE005", "SYSTEM * OCSE * SNAP eligible items charge in CC"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APMS002", "SYSTEM * AcuPick * Missing Order"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APPS003", "SYSTEM * AcuPick * PPD Scanning Issue"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APPD004", "SYSTEM * AcuPick * PPD Connection Issue"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APII010", "SYSTEM * AcuPick * Incorrect Item error during picking"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APIID022", "SYSTEM * AcuPick * Missing item images/descriptions in picklist"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APINA024", "SYSTEM * AcuPick * Item not available error when picking"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APIIZ025", "SYSTEM * AcuPick * Incorrect item zone"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APZAC026", "SYSTEM * AcuPick * Orders are picked - Zero amount charged"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APMAP027", "SYSTEM * AcuPick * Mapping Issue"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APRES028", "SYSTEM * AcuPick * Customer pickup procedure - PPD does not recognized restricted item"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APNRG029", "SYSTEM * AcuPick * Kept on asking valid ID for non-regulated items"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APPRO031", "SYSTEM * AcuPick * Multiplying the qty/weight of produce items"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APRSP033", "SYSTEM * AcuPick * Reshop issue"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APBAG034", "SYSTEM * Acupick * app should not ask for bag count since store does not charge bag fee"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APSUB035", "SYSTEM * AcuPick * Unable to substitute, complete box is missing"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APQTY036", "SYSTEM * AcuPick * Items sold by qty is asking to sub as weighted"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APNEG038", "SYSTEM * AcuPick * Negative picked qty"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APVER039", "SYSTEM * AcuPick * App version is not updated"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APARR040", "SYSTEM * AcuPick * Unable to Mark as Arrived in PPD"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APDKE041", "SYSTEM * AcuPick * Staging - Duplicate Key Error"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APPRD042", "SYSTEM * AcuPick * Produce items are not scanning forcing picker to perform substitution"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APUNR043", "SYSTEM * AcuPick * Unreleased Orders"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APQOW044", "SYSTEM * AcuPick * items should be sold by quantity, not weight or vice versa"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APSTG045", "SYSTEM * AcuPick * Staging Issue - printing labels for a diff customer"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APSEL046", "SYSTEM * Acupick * Error printing labels - config issue"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APSTG047", "SYSTEM * AcuPick * Order Staging - keeps on asking bag/loose count after scanning bag labels"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APONE048", "SYSTEM * AcuPick * Acupick dashboard shows 1 as the total no. of items"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APNPCK049", "SYSTEM * AcuPick * No picklists generated for Ready to Pick orders"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APIMG050", "SYSTEM * AcuPick * Incorrect item image/description in picklist"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APOOS051", "SYSTEM * AcuPick * Items in order automatically go out of stock"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APIID052", "SYSTEM * Acupick * Incorrect item description"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APMEX053", "SYSTEM * AcuPick * MTO items on Express orders"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APPGR054", "SYSTEM * AcuPick * Pick quantity is greater than remaining quantity error"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APARV055", "SYSTEM * AcuPick * Not receiving arrival notification on picking device"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APREG056", "SYSTEM * AcuPick * Regulated Item not asking for ID"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APEXN057", "SYSTEM * AcuPick * Not receiving Express order drop notification"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APFIX058", "SYSTEM * AcuPick * Fixed Item Type Issue"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APNSN059", "SYSTEM * AcuPick * No SHIPT arrival notification received on PPDs"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APBOF60", "SYSTEM * AcuPick * Batched orders failing to complete - Rescheduling"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APOSTI61", "SYSTEM * AcuPick * Order stage time is incorrect"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APOH063", "SYSTEM * AcuPick * Order Handoff - This order is already assigned to another associate"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APREJ064", "SYSTEM * AcuPick * No notification of customer rejected substitution"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APPOS065", "SYSTEM * AcuPick * Item was picked but shows OOS in receipt - Picked info from APS was not processed"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APPPI066", "SYSTEM * AcuPick * Item was picked but wasn't charged - Picked info from APS was not processed"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APONF67", "SYSTEM * AcuPick * Order not flowing to VPOS - qty 0.0 issue on JSON file (fulfilledUPC is null)"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APONF68", "SYSTEM * AcuPick * Order not flowing to VPOS - qty negative issue on JSON file (substituted item)"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APONF69", "SYSTEM * AcuPick * Order not flowing to VPOS - Replicator topics causing lag"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APHOT70", "SYSTEM * AcuPick * Handoff timer triggered before arrival / Ghost notification"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APBNSC71", "SYSTEM * Acupick * Scanning specific item crashes the AcuPick app"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APECQ72", "SYSTEM * Acupick * PPD Error - Error Computing quantity"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APCRS73", "SYSTEM * Acupick * Customer rejected all the subs items and cancelled the order but it got charged"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APPENT74", "SYSTEM * Acupick * PPD Error - No Item Scanned"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APPEWS75", "SYSTEM * Acupick * PPD Error - Wrong Item Scanned"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APSTA76", "SYSTEM * Acupick * SHIP-TO Address is Blank/Incomplete"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APAPS77", "SYSTEM * Acupick * Acupick app stops when doing substitution"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APARS78", "SYSTEM * Acupick * Order stuck in Awaiting Release Status"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APPRS79", "SYSTEM * Acupick * Order Stuck in Picked Up - Payment Requested Status"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APGEB80", "SYSTEM * Acupick * Order generating extra bag tags"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APHBM81", "SYSTEM * AcuPick * Verify code button disappear when Store enter a wrong auth code first time"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APNHT82", "SYSTEM * AcuPick * No handoff timer for 3PL order"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APNVA83", "SYSTEM * Acupick * Van IDs are not showing up on the picklist tab - only the truck icon"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APACR84", "SYSTEM * Acupick * Awaiting Customer Response in Acupick but shows as cancelled in ECHO"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APNAV85", "SYSTEM * Acupick * Order has an alcohol but not prompting for Age verification"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APSIC86", "SYSTEM * AcuPick * Order not flowing to Vtill - stuck in Staging Complete in Acupick"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APIP011", "SYSTEM * AcuPick * Order stuck in In Progress / PPD 400 error"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APICA12", "SYSTEM * AcuPick * Order stuck in In Progress; Cancelled activity"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APPDP87", "SYSTEM * AcuPick * Preplist Duplicate Printing"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APFLN089", "SYSTEM * AcuPick * Not receiving FLASH order drop notification"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APNGT090", "SYSTEM * AcuPick * Timer starting off on negative count"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APRUT091", "SYSTEM * AcuPick * Timer keeps on running after handoff"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APNRT092", "SYSTEM * AcuPick * Timer is not running"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APPNI093", "SYSTEM * AcuPick * Pre-pick order - Preplist Notification Issue"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APIRS094", "SYSTEM * Acupick * Item rejected at Store"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APCTU095", "SYSTEM * Acupick * Complete order in TakeOff is unreleased in Acupick"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APSIP96", "SYSTEM * Acupick * Order stuck in Pending Release"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APSOP97", "SYSTEM * Acupick * Order Duplicate Picklists issue"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APRSP98", "SYSTEM * Acupick * Resolve Exception status in Acupick but Pickup Ready in VTILL"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APISM99", "SYSTEM * Acupick * Item incorrectly showing as MTO"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APSPB100", "SYSTEM * Acupick * substituting produce - select quantity button not working"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APSDC101", "SYSTEM * Acupick * Handoff stucked: Do you want to begin or continue staging?"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APNOA102", "SYSTEM * Acupick * No order arrival received - Error loading data. There was a error loading arrivals data on Acupick"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APINS103", "SYSTEM * Acupick * Images are slow/not loading in picking devices"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APUAL104", "SYSTEM * Acupick * Unable to access tote labels to print"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APDIE105", "SYSTEM * Acupick * Deli item error - Amount enter is too heavy, check with department"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APAID106", "SYSTEM * Acupick * Acupick is Down"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APAPIE107", "SYSTEM * Acupick * Unable to stage order - API Response Error"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APUNA108", "SYSTEM * Acupick * Picked order still shows Ready to Pick in Acupick"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APCND109", "SYSTEM * Acupick * Chat assist will not display shop assist messages"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APCGA110", "SYSTEM * Acupick * Chat gets activated earlier than expected"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APOAR111", "SYSTEM * Acupick * Orders at risk are not highlighted as Red/Pink"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APPZIQ112", "SYSTEM * Acupick * Picklist shows Zero Item Qty"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APNODK113", "SYSTEM * Acupick * No Order Details in Dashboard due to Duplicate lineID"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APPNRNO114", "SYSTEM * Acupick * PPDs not receiving notifications when new orders come in"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APPRXOD115", "SYSTEM * Acupick * RX Orders Showing Zero Items in PPD"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APWINSC116", "SYSTEM * Acupick * Weight-based items not scanning correctly"),
    ("SYSTEM", "eCom Picking Mgmt. System (OSPK)", "APTCORBP117", "SYSTEM * Acupick * App crashes whenever Tote Count is Less Than Order Count for a Rolling Batch Picklist"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP001", "OPS * AcuPick * Switch Label Printer"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP002", "OPS * AcuPick * Order Cancellation Request"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP003", "OPS * AcuPick * Password Reset"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP005", "OPS * AcuPick * Add/Update Account Request"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP006", "OPS * Acupick * Store Inquires if order is charged"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP007", "OPS * Acupick * Store Inquires if there are orders for the day"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP008", "OPS * Acupick * orders dropping randomly instead of in a sequence"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP009", "OPS * Acupick * Store is not yet done picking the order"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP010", "OPS * Acupick * Store inquiry about a future order"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP011", "OPS * Acupick * Deployment - orders are not dropping to AcuPick"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP012", "OPS * Acupick * User Error - Label printer is OFF"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP013", "OPS * Acupick * Training Issue - incorrect picked qty"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP015", "OPS * Acupick * Newly migrated Acupick store is looking for orders in Manhattan"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP016", "OPS * Acupick * Store reports that they get orders outside the store's pickup schedule"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP017", "OPS * Acupick * Store reports order is not in VTill but it is there when checked"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP018", "OPS * Acupick * Store reports they can't complete/stage order but order is complete"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP019", "OPS * Acupick * Acupick dashboard is not responding/loading"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP021", "OPS * Acupick * Early order drop in PPD"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP023", "OPS * Acupick * Order was accidentally marked as picked up"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP024", "OPS * Acupick * Existing picker in Acupick is unable to login"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP025", "OPS * Acupick * User accidentally logged in to other store and is now unable to take out the order"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP026", "OPS * Acupick * Request to change order type"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP027", "OPS * Acupick * Produce Scale Issue"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP028", "OPS * Acupick * Store inquiry about past orders"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP029", "OPS * Acupick * Store request to edit items on today's order"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APLG001", "OPS * Acupick * Login Issue - Network Error / An error occurred. Please try again"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APLP005", "OPS * AcuPick * Label Printing Issue"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APCPU016", "OPS * AcuPick * Unable to confirm pickup of order"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP031", "OPS * AcuPick * Training Issue - Staging an Order"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP032", "OPS * AcuPick * Training Issue - Order Handoff"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP033", "OPS * Acupick * Training Issue - Order Drop Schedule"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP034", "OPS * Acupick * Request to drop test order"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP035", "OPS * Acupick * Reassign activity - Original Picker did not complete staging the order"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP036", "OPS * Acupick * Training issue - Reassign picklist"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP037", "OPS * Acupick * Inquiry for splitting order into multiple picklists"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP038", "OPS * Acupick * Store is using incorrect AcuPick dashboard link"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP040", "OPS * Acupick * Store Request - Transfer order to a different store"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP041", "OPS * AcuPick * Store inquiry on cancelled order"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP042", "OPS * AcuPick * Training Issue - Express Order Cut-off time"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP043", "OPS * AcuPick * User Error - accidentally OOS items"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOPRI44", "OPS * AcuPick * Remove/Add Item to Catalog Request"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP045", "OPS * Acupick * Training issue - Scanning item"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP046", "OPS * AcuPick * Store Slot Inquiry"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOAC47", "OPS * Acupick * Awaiting Customer Response - waiting for the customer to approved subbed items"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APORE48", "OPS * Acupick * Resolve Exception status in Acupick - waiting for store to process fixable VPOS exception"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APOP049", "OPS * AcuPick * Inquiry on item missing in receipt but item substitution was rejected"),
    ("OPS", "eCom Picking Mgmt. System (OSPK)", "APODB01", "OPS * AcuPick * Training Issue - Dynamic Batch Orders showing Ready to Pick"),
    ("PE", "eCom Picking Mgmt. System (OSPK)", "APOP004", "PE * AcuPick * Redrop past order request / reschedule order"),
    ("PE", "eCom Picking Mgmt. System (OSPK)", "APND009", "PE * AcuPick * Order is showing Ready to Pick and not dropping to PPD"),
    ("PE", "eCom Picking Mgmt. System (OSPK)", "APIBR49", "PE * AcuPick * Order IN PROGRESS in Acupick but PICKUP READY in VTILL"),
    ("PE", "eCom Picking Mgmt. System (OSPK)", "APNCA018", "PE * AcuPick * Order is cancelled in OSCO but not in AcuPick"),
    ("PE", "eCom Picking Mgmt. System (OSPK)", "APPRP021", "PE * AcuPick * Preplist is not printing / missing items in preplist"),
    ("PE", "eCom Picking Mgmt. System (OSPK)", "APACN044", "PE * AcuPick * Order stuck in Awaiting Consol"),
    ("SYSTEM", "eCommerce Order Mgmt. System (for Micro Fulfillment Center) (OSCO)", "OSCO001", "SYSTEM * OSCO * Order not flowing to Vtill - stuck in Packed in OSCO"),
    ("SYSTEM", "eCommerce Order Mgmt. System (for Micro Fulfillment Center) (OSCO)", "OSCO002", "SYSTEM * OSCO * Order not flowing to Vtill - already in Payment Requested in OSCO"),
    ("SYSTEM", "eCommerce Order Mgmt. System (for Micro Fulfillment Center) (OSCO)", "OSCO003", "SYSTEM * OSCO * Order in Pickup ready status is not flowing to VTill - Released in OSCO"),
    ("SYSTEM", "eCommerce Order Mgmt. System (for Micro Fulfillment Center) (OSCO)", "OSCO004", "SYSTEM * OSCO * Order not flowing to Vtill - PICK_START in OSCO"),
    ("SYSTEM", "eCommerce Order Mgmt. System (for Micro Fulfillment Center) (OSCO)", "OSCO005", "SYSTEM * OSCO * Order not flowing to Vtill - multiple versions"),
    ("SYSTEM", "eCommerce Order Mgmt. System (for Micro Fulfillment Center) (OSCO)", "MFCOV001", "SYSTEM * MFC * MFC Orders not dropping to Vtill"),
    ("SYSTEM", "eCommerce Order Mgmt. System (for Micro Fulfillment Center) (OSCO)", "OSCO006", "SYSTEM * OSCO * Overcharged order (OSCO sending qty as 1 as part of pricing request for the OOS items with upc starting with 02)"),
    ("SYSTEM", "eCommerce Order Mgmt. System (for Micro Fulfillment Center) (OSCO)", "OSCO007", "SYSTEM * OSCO * Missing in Takeoff"),
    ("SYSTEM", "eCommerce Order Mgmt. System (for Micro Fulfillment Center) (OSCO)", "OSCO008", "SYSTEM * OSCO * Order not flowing to Vtill - stuck in PICKED_UP in OSCO"),
    ("SYSTEM", "eCommerce Order Mgmt. System (for Micro Fulfillment Center) (OSCO)", "OSCO009", "SYSTEM * OSCO * Order not flowing to Vtill - stuck in PRICED in OSCO"),
    ("SYSTEM", "eCommerce Order Mgmt. System (for Micro Fulfillment Center) (OSCO)", "OSCO010", "SYSTEM * OSCO * Order not flowing to Vtill - Stuck in Pending Payment Status in Acupick"),
    ("SYSTEM", "eCommerce Order Mgmt. System (for Micro Fulfillment Center) (OSCO)", "OSCO011", "SYSTEM * OSCO * Order not flowing to Vtill - Stuck in STAGED status in OSCO"),
    ("SYSTEM", "eCommerce Order Mgmt. System (for Micro Fulfillment Center) (OSCO)", "OSCO012", "SYSTEM * OSCO * Order not flowing to Vtill - Stuck in PACKED and In Progress in Acupick (Complete FulfilledUPC) - with FAS error"),
    ("SYSTEM", "eCommerce Order Mgmt. System (for Micro Fulfillment Center) (OSCO)", "OSCO013", "SYSTEM * OSCO * Order not flowing to Vtill - Stuck in PACKED and In Progress in Acupick"),
    ("SYSTEM", "eCommerce Order Mgmt. System (for Micro Fulfillment Center) (OSCO)", "OSCO014", "SYSTEM * OSCO * Order not flowing to Vtill - Stuck in PACKED due to Large Order"),
    ("SYSTEM", "eCom Online Shopping Last Mile (OSLM)", "3PL001", "SYSTEM * 3PL * Unable to login to Doordash"),
    ("SYSTEM", "eCom Online Shopping Last Mile (OSLM)", "3PL002", "SYSTEM * 3PL * Unable to login to Point pickup"),
    ("SYSTEM", "eCom Online Shopping Last Mile (OSLM)", "3PL003", "SYSTEM * 3PL * Order not flowing to Doordash / Point pickup"),
    ("SYSTEM", "eCom Online Shopping Last Mile (OSLM)", "3PL004", "SYSTEM * 3PL * 3PL Portal is not loading"),
    ("SYSTEM", "eCom Online Shopping Last Mile (OSLM)", "3PL005", "SYSTEM * 3PL * The PA notification chimes not going off at customers check in/arrival"),
    ("SYSTEM", "Descartes Route Planner (OSRP)", "RP001", "SYSTEM * OSRP * Cancelled order - Order Release Failure"),
    ("SYSTEM", "Descartes Route Planner (OSRP)", "RP002", "SYSTEM * OSRP * Cancelled orders are not flowing to RP from EOM correctly"),
    ("SYSTEM", "Descartes Route Planner (OSRP)", "RP003", "SYSTEM * OSRP * Duplicate order in Van Trip Summary"),
    ("SYSTEM", "Descartes Route Planner (OSRP)", "RP004", "SYSTEM * OSRP * Early Van Allocation"),
    ("SYSTEM", "Descartes Route Planner (OSRP)", "RP005", "SYSTEM * OSRP * Incorrect Van Departure Time"),
    ("SYSTEM", "Descartes Route Planner (OSRP)", "RP006", "SYSTEM * OSRP * Missing vans for multiple stores"),
    ("SYSTEM", "Descartes Route Planner (OSRP)", "RP007", "SYSTEM * OSRP * missing in RP"),
    ("SYSTEM", "Descartes Route Planner (OSRP)", "RP008", "SYSTEM * OSRP * No response from RP to EOM"),
    ("SYSTEM", "Descartes Route Planner (OSRP)", "RP009", "SYSTEM * OSRP * Optimization issue - too much orders in 1 van"),
    ("SYSTEM", "Descartes Route Planner (OSRP)", "RP010", "SYSTEM * OSRP * Order not in AVL"),
    ("SYSTEM", "Descartes Route Planner (OSRP)", "RP011", "SYSTEM * OSRP * Orders not dropping (RP issue)"),
    ("SYSTEM", "Descartes Route Planner (OSRP)", "RP012", "SYSTEM * OSRP * RouteInfoUpdate - ABORTED"),
    ("SYSTEM", "Descartes Route Planner (OSRP)", "RP013", "SYSTEM * OSRP * RP DB logs full"),
    ("SYSTEM", "Descartes Route Planner (OSRP)", "RP014", "SYSTEM * OSRP * Stuck in Review"),
    ("SYSTEM", "Descartes Route Planner (OSRP)", "RP015", "SYSTEM * OSRP * scheduler configuration issue"),
    ("SYSTEM", "Descartes Route Planner (OSRP)", "RP016", "SYSTEM * OSRP * UI failed to load"),
    ("SYSTEM", "Descartes Route Planner (OSRP)", "RP017", "SYSTEM * OSRP * Unwaved Orders (DST Change)"),
    ("SYSTEM", "Salesforce Marketing Cloud (EMSF)", "EMSF001", "SYSTEM * EMSF * Not sending arrival notification to DUG phones"),
    ("SYSTEM", "Salesforce Marketing Cloud (EMSF)", "EMSF002", "SYSTEM * EMSF * Delay in receiving arrival notifications on DUG phones"),
    ("SYSTEM", "Salesforce Marketing Cloud (EMSF)", "EMSF003", "SYSTEM * EMSF * Not sending Delivered/Delivery on the way notification to customer"),
    ("SYSTEM", "Salesforce Marketing Cloud (EMSF)", "EMSF004", "SYSTEM * EMSF * Customer unable to check in on App"),
    ("OPS", "Salesforce Marketing Cloud (EMSF)", "EMSFOP1", "OPS * EMSF * DUG Phones not receive notification when customer presses ON THE WAY from the app"),
    ("OPS", "eCom Customer Order - Control Tower (OSCT)", "CT0001", "OPS * Control Tower * Site is showing 404 Not Found - Order is showing no record found"),
    ("SYSTEM", "Online Shopping Demand Planning (OSDP)", "OSDP001", "SYSTEM * OSDP * Customer can't see slot capacity"),
    ("SYSTEM", "Online Shopping Demand Planning (OSDP)", "OSDP002", "SYSTEM * OSDP * Unable to access eCom Operations App"),
]


def get_conn() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db():
    with get_conn() as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS tracking_ref (
                id            INTEGER PRIMARY KEY AUTOINCREMENT,
                type          TEXT NOT NULL,
                ci            TEXT NOT NULL,
                tracking_code TEXT NOT NULL UNIQUE,
                category      TEXT NOT NULL
            )
        """)
        # Always sync SEED_DATA — insert new codes, skip existing ones
        clean = [
            (t, ci, code, cat)
            for t, ci, code, cat in SEED_DATA
            if code and code.strip()
        ]
        conn.executemany(
            "INSERT OR REPLACE INTO tracking_ref (type, ci, tracking_code, category) VALUES (?,?,?,?)",
            clean
        )
        conn.commit()


def get_all_tracking() -> list[dict]:
    with get_conn() as conn:
        rows = conn.execute(
            "SELECT id, type, ci, tracking_code, category FROM tracking_ref ORDER BY ci, tracking_code"
        ).fetchall()
    return [dict(r) for r in rows]


def upsert_tracking(id: int | None, type_: str, ci: str, tracking_code: str, category: str) -> dict:
    with get_conn() as conn:
        if id:
            conn.execute(
                "UPDATE tracking_ref SET type=?, ci=?, tracking_code=?, category=? WHERE id=?",
                (type_, ci, tracking_code, category, id)
            )
        else:
            conn.execute(
                "INSERT INTO tracking_ref (type, ci, tracking_code, category) VALUES (?,?,?,?)",
                (type_, ci, tracking_code, category)
            )
        conn.commit()
        row = conn.execute(
            "SELECT id, type, ci, tracking_code, category FROM tracking_ref WHERE tracking_code=?",
            (tracking_code,)
        ).fetchone()
    return dict(row)


def delete_tracking(id: int):
    with get_conn() as conn:
        conn.execute("DELETE FROM tracking_ref WHERE id=?", (id,))
        conn.commit()


def get_tracking_map() -> dict:
    rows = get_all_tracking()
    return {r["tracking_code"]: r for r in rows}


def get_ci_type_map() -> dict:
    rows = get_all_tracking()
    return {r["ci"]: r["type"] for r in rows}